# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basler.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 615)
        MainWindow.setMaximumSize(QtCore.QSize(924, 615))
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxLeds = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxLeds.setGeometry(QtCore.QRect(570, 0, 341, 391))
        self.groupBoxLeds.setObjectName("groupBoxLeds")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxLeds)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 355))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.yellowLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.yellowLed.setObjectName("yellowLed")
        self.gridLayout.addWidget(self.yellowLed, 9, 0, 1, 1)
        self.blueLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.blueLed.setObjectName("blueLed")
        self.gridLayout.addWidget(self.blueLed, 0, 0, 1, 1)
        self.chartreuseLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.chartreuseLed.setObjectName("chartreuseLed")
        self.gridLayout.addWidget(self.chartreuseLed, 1, 0, 1, 1)
        self.ultravioletLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ultravioletLed.setObjectName("ultravioletLed")
        self.gridLayout.addWidget(self.ultravioletLed, 7, 0, 1, 1)
        self.greenLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.greenLed.setObjectName("greenLed")
        self.gridLayout.addWidget(self.greenLed, 4, 0, 1, 1)
        self.deepredLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.deepredLed.setObjectName("deepredLed")
        self.gridLayout.addWidget(self.deepredLed, 3, 0, 1, 1)
        self.infraredLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.infraredLed.setObjectName("infraredLed")
        self.gridLayout.addWidget(self.infraredLed, 5, 0, 1, 1)
        self.cyanLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cyanLed.setObjectName("cyanLed")
        self.gridLayout.addWidget(self.cyanLed, 2, 0, 1, 1)
        self.redLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.redLed.setObjectName("redLed")
        self.gridLayout.addWidget(self.redLed, 6, 0, 1, 1)
        self.violetLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.violetLed.setObjectName("violetLed")
        self.gridLayout.addWidget(self.violetLed, 8, 0, 1, 1)
        self.wheelLed = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.wheelLed.setObjectName("wheelLed")
        self.gridLayout.addWidget(self.wheelLed, 10, 0, 1, 1)
        self.dial = QtWidgets.QDial(self.groupBoxLeds)
        self.dial.setGeometry(QtCore.QRect(190, 120, 141, 151))
        self.dial.setStyleSheet("")
        self.dial.setMaximum(100)
        self.dial.setProperty("value", 0)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setObjectName("dial")
        self.lcdPwm = QtWidgets.QLCDNumber(self.groupBoxLeds)
        self.lcdPwm.setGeometry(QtCore.QRect(210, 50, 81, 51))
        self.lcdPwm.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdPwm.setDigitCount(3)
        self.lcdPwm.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdPwm.setProperty("intValue", 0)
        self.lcdPwm.setObjectName("lcdPwm")
        self.label = QtWidgets.QLabel(self.groupBoxLeds)
        self.label.setGeometry(QtCore.QRect(220, 30, 67, 17))
        self.label.setObjectName("label")
        self.ledsOffButton = QtWidgets.QPushButton(self.groupBoxLeds)
        self.ledsOffButton.setGeometry(QtCore.QRect(220, 280, 89, 25))
        self.ledsOffButton.setObjectName("ledsOffButton")
        self.cameraTab = QtWidgets.QTabWidget(self.centralwidget)
        self.cameraTab.setGeometry(QtCore.QRect(0, 0, 551, 571))
        self.cameraTab.setObjectName("cameraTab")
        self.cameraParameters = QtWidgets.QWidget()
        self.cameraParameters.setObjectName("cameraParameters")
        self.groupBox = QtWidgets.QGroupBox(self.cameraParameters)
        self.groupBox.setGeometry(QtCore.QRect(50, 110, 201, 211))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 30, 191, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editWidth = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.editWidth.setObjectName("editWidth")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editWidth)
        self.editHeight = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.editHeight.setObjectName("editHeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editHeight)
        self.comboBoxPixelFormat = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxPixelFormat.setObjectName("comboBoxPixelFormat")
        self.comboBoxPixelFormat.addItem("")
        self.comboBoxPixelFormat.addItem("")
        self.comboBoxPixelFormat.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxPixelFormat)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBoxOutputBit = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxOutputBit.setObjectName("comboBoxOutputBit")
        self.comboBoxOutputBit.addItem("")
        self.comboBoxOutputBit.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxOutputBit)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBoxFormat = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.comboBoxFormat.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBoxFormat)
        self.groupBox_2 = QtWidgets.QGroupBox(self.cameraParameters)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 340, 351, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 341, 121))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBoxExposure = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBoxExposure.setEditable(False)
        self.comboBoxExposure.setObjectName("comboBoxExposure")
        self.comboBoxExposure.addItem("")
        self.comboBoxExposure.addItem("")
        self.comboBoxExposure.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxExposure)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.editExposure = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.editExposure.setObjectName("editExposure")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editExposure)
        self.checkBoxAFR = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBoxAFR.setChecked(False)
        self.checkBoxAFR.setObjectName("checkBoxAFR")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBoxAFR)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.editFrameRate = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.editFrameRate.setEnabled(False)
        self.editFrameRate.setObjectName("editFrameRate")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editFrameRate)
        self.groupBox_3 = QtWidgets.QGroupBox(self.cameraParameters)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 20, 181, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.labelCameraInfo = QtWidgets.QLabel(self.groupBox_3)
        self.labelCameraInfo.setGeometry(QtCore.QRect(20, 30, 151, 17))
        self.labelCameraInfo.setObjectName("labelCameraInfo")
        self.pushButtonConnect = QtWidgets.QPushButton(self.cameraParameters)
        self.pushButtonConnect.setGeometry(QtCore.QRect(250, 50, 89, 25))
        self.pushButtonConnect.setCheckable(False)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.groupBox_4 = QtWidgets.QGroupBox(self.cameraParameters)
        self.groupBox_4.setGeometry(QtCore.QRect(290, 140, 191, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 175, 121))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBoxGain = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBoxGain.setObjectName("comboBoxGain")
        self.comboBoxGain.addItem("")
        self.comboBoxGain.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxGain)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.editGain = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.editGain.setText("")
        self.editGain.setObjectName("editGain")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editGain)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.editGamma = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.editGamma.setObjectName("editGamma")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editGamma)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.comboBoxDigitalShift = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBoxDigitalShift.setObjectName("comboBoxDigitalShift")
        self.comboBoxDigitalShift.addItem("")
        self.comboBoxDigitalShift.addItem("")
        self.comboBoxDigitalShift.addItem("")
        self.comboBoxDigitalShift.addItem("")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBoxDigitalShift)
        self.pushButtonSetParameters = QtWidgets.QPushButton(self.cameraParameters)
        self.pushButtonSetParameters.setEnabled(False)
        self.pushButtonSetParameters.setGeometry(QtCore.QRect(360, 50, 111, 25))
        self.pushButtonSetParameters.setObjectName("pushButtonSetParameters")
        self.cameraTab.addTab(self.cameraParameters, "")
        self.calibration = QtWidgets.QWidget()
        self.calibration.setObjectName("calibration")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.calibration)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 368, 521, 121))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.setpointScrollCalibration = QtWidgets.QScrollBar(self.gridLayoutWidget_6)
        self.setpointScrollCalibration.setEnabled(True)
        self.setpointScrollCalibration.setMaximum(255)
        self.setpointScrollCalibration.setOrientation(QtCore.Qt.Horizontal)
        self.setpointScrollCalibration.setObjectName("setpointScrollCalibration")
        self.gridLayout_6.addWidget(self.setpointScrollCalibration, 0, 1, 1, 1)
        self.gainScrollCalibration = QtWidgets.QScrollBar(self.gridLayoutWidget_6)
        self.gainScrollCalibration.setEnabled(True)
        self.gainScrollCalibration.setMaximum(36)
        self.gainScrollCalibration.setOrientation(QtCore.Qt.Horizontal)
        self.gainScrollCalibration.setObjectName("gainScrollCalibration")
        self.gridLayout_6.addWidget(self.gainScrollCalibration, 1, 1, 1, 1)
        self.exposureScrollCalibration = QtWidgets.QScrollBar(self.gridLayoutWidget_6)
        self.exposureScrollCalibration.setEnabled(True)
        self.exposureScrollCalibration.setMinimum(27)
        self.exposureScrollCalibration.setMaximum(10000000)
        self.exposureScrollCalibration.setOrientation(QtCore.Qt.Horizontal)
        self.exposureScrollCalibration.setObjectName("exposureScrollCalibration")
        self.gridLayout_6.addWidget(self.exposureScrollCalibration, 2, 1, 1, 1)
        self.setpointEditCalibration = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.setpointEditCalibration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditCalibration.sizePolicy().hasHeightForWidth())
        self.setpointEditCalibration.setSizePolicy(sizePolicy)
        self.setpointEditCalibration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditCalibration.setObjectName("setpointEditCalibration")
        self.gridLayout_6.addWidget(self.setpointEditCalibration, 0, 2, 1, 1)
        self.gainEditCalibration = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.gainEditCalibration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditCalibration.sizePolicy().hasHeightForWidth())
        self.gainEditCalibration.setSizePolicy(sizePolicy)
        self.gainEditCalibration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditCalibration.setObjectName("gainEditCalibration")
        self.gridLayout_6.addWidget(self.gainEditCalibration, 1, 2, 1, 1)
        self.exposureEditCalibration = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.exposureEditCalibration.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditCalibration.sizePolicy().hasHeightForWidth())
        self.exposureEditCalibration.setSizePolicy(sizePolicy)
        self.exposureEditCalibration.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditCalibration.setObjectName("exposureEditCalibration")
        self.gridLayout_6.addWidget(self.exposureEditCalibration, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_21.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.calibration)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(9, 490, 521, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.startButton2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.startButton2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton2.setFont(font)
        self.startButton2.setAutoFillBackground(True)
        self.startButton2.setObjectName("startButton2")
        self.horizontalLayout_4.addWidget(self.startButton2)
        self.stopButton2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopButton2.setFont(font)
        self.stopButton2.setObjectName("stopButton2")
        self.horizontalLayout_4.addWidget(self.stopButton2)
        self.loadCalibration = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadCalibration.setFont(font)
        self.loadCalibration.setObjectName("loadCalibration")
        self.horizontalLayout_4.addWidget(self.loadCalibration)
        self.calibrateSaveFile = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.calibrateSaveFile.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.calibrateSaveFile.setFont(font)
        self.calibrateSaveFile.setObjectName("calibrateSaveFile")
        self.horizontalLayout_4.addWidget(self.calibrateSaveFile)
        self.checkBoxcalibrate = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxcalibrate.setFont(font)
        self.checkBoxcalibrate.setObjectName("checkBoxcalibrate")
        self.horizontalLayout_4.addWidget(self.checkBoxcalibrate)
        self.calibrationModeVideoState = QtWidgets.QGroupBox(self.calibration)
        self.calibrationModeVideoState.setGeometry(QtCore.QRect(10, 0, 531, 351))
        self.calibrationModeVideoState.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.calibrationModeVideoState.setObjectName("calibrationModeVideoState")
        self.calibrationImage = QtWidgets.QLabel(self.calibrationModeVideoState)
        self.calibrationImage.setGeometry(QtCore.QRect(0, 20, 531, 331))
        self.calibrationImage.setText("")
        self.calibrationImage.setObjectName("calibrationImage")
        self.cameraTab.addTab(self.calibration, "")
        self.manualMode = QtWidgets.QWidget()
        self.manualMode.setObjectName("manualMode")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.manualMode)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 469, 481, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.stopCamera = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopCamera.setFont(font)
        self.stopCamera.setObjectName("stopCamera")
        self.horizontalLayout.addWidget(self.stopCamera)
        self.snapshot = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.snapshot.setFont(font)
        self.snapshot.setObjectName("snapshot")
        self.horizontalLayout.addWidget(self.snapshot)
        self.saveSnapshot = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveSnapshot.setFont(font)
        self.saveSnapshot.setObjectName("saveSnapshot")
        self.horizontalLayout.addWidget(self.saveSnapshot)
        self.manualModeVideoState = QtWidgets.QGroupBox(self.manualMode)
        self.manualModeVideoState.setGeometry(QtCore.QRect(10, 0, 531, 451))
        self.manualModeVideoState.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.manualModeVideoState.setObjectName("manualModeVideoState")
        self.imageLabel = QtWidgets.QLabel(self.manualModeVideoState)
        self.imageLabel.setGeometry(QtCore.QRect(0, 20, 531, 431))
        self.imageLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.cameraTab.addTab(self.manualMode, "")
        self.automaticMode = QtWidgets.QWidget()
        self.automaticMode.setObjectName("automaticMode")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.automaticMode)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 521, 415))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.exposureEditAutomatic9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic9.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic9.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic9.setObjectName("exposureEditAutomatic9")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic9, 10, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 2, 1, 1)
        self.exposureEditAutomatic8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic8.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic8.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic8.setObjectName("exposureEditAutomatic8")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic8, 9, 5, 1, 1)
        self.imagesEditAutomatic1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic1.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic1.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic1.setObjectName("imagesEditAutomatic1")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic1, 2, 3, 1, 1)
        self.imagesEditAutomatic4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic4.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic4.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic4.setObjectName("imagesEditAutomatic4")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic4, 5, 3, 1, 1)
        self.exposureEditAutomatic2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic2.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic2.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic2.setObjectName("exposureEditAutomatic2")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic2, 3, 5, 1, 1)
        self.imagesEditAutomatic3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic3.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic3.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic3.setObjectName("imagesEditAutomatic3")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic3, 4, 3, 1, 1)
        self.gainEditAutomatic8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic8.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic8.setSizePolicy(sizePolicy)
        self.gainEditAutomatic8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic8.setObjectName("gainEditAutomatic8")
        self.gridLayout_2.addWidget(self.gainEditAutomatic8, 9, 4, 1, 1)
        self.imagesEditAutomatic6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic6.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic6.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic6.setObjectName("imagesEditAutomatic6")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic6, 7, 3, 1, 1)
        self.imagesEditAutomatic9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic9.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic9.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic9.setObjectName("imagesEditAutomatic9")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic9, 10, 3, 1, 1)
        self.setpointEditAutomatic7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic7.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic7.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic7.setObjectName("setpointEditAutomatic7")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic7, 8, 2, 1, 1)
        self.comboBoxLed7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed7.setObjectName("comboBoxLed7")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.comboBoxLed7.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed7, 8, 0, 1, 1)
        self.spinBoxPwm2 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm2.setEnabled(True)
        self.spinBoxPwm2.setMaximum(100)
        self.spinBoxPwm2.setObjectName("spinBoxPwm2")
        self.gridLayout_2.addWidget(self.spinBoxPwm2, 3, 1, 1, 1)
        self.spinBoxPwm8 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm8.setEnabled(True)
        self.spinBoxPwm8.setMaximum(100)
        self.spinBoxPwm8.setObjectName("spinBoxPwm8")
        self.gridLayout_2.addWidget(self.spinBoxPwm8, 9, 1, 1, 1)
        self.spinBoxPwm1 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm1.setEnabled(True)
        self.spinBoxPwm1.setMaximum(100)
        self.spinBoxPwm1.setObjectName("spinBoxPwm1")
        self.gridLayout_2.addWidget(self.spinBoxPwm1, 2, 1, 1, 1)
        self.spinBoxPwm4 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm4.setEnabled(True)
        self.spinBoxPwm4.setMaximum(100)
        self.spinBoxPwm4.setObjectName("spinBoxPwm4")
        self.gridLayout_2.addWidget(self.spinBoxPwm4, 5, 1, 1, 1)
        self.spinBoxPwm0 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm0.setEnabled(True)
        self.spinBoxPwm0.setMaximum(100)
        self.spinBoxPwm0.setObjectName("spinBoxPwm0")
        self.gridLayout_2.addWidget(self.spinBoxPwm0, 1, 1, 1, 1)
        self.spinBoxPwm5 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm5.setEnabled(True)
        self.spinBoxPwm5.setMaximum(100)
        self.spinBoxPwm5.setObjectName("spinBoxPwm5")
        self.gridLayout_2.addWidget(self.spinBoxPwm5, 6, 1, 1, 1)
        self.spinBoxPwm9 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm9.setEnabled(True)
        self.spinBoxPwm9.setMaximum(100)
        self.spinBoxPwm9.setObjectName("spinBoxPwm9")
        self.gridLayout_2.addWidget(self.spinBoxPwm9, 10, 1, 1, 1)
        self.comboBoxLed6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed6.setObjectName("comboBoxLed6")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.comboBoxLed6.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed6, 7, 0, 1, 1)
        self.comboBoxLed8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed8.setObjectName("comboBoxLed8")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.comboBoxLed8.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed8, 9, 0, 1, 1)
        self.setpointEditAutomatic0 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic0.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic0.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic0.setObjectName("setpointEditAutomatic0")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic0, 1, 2, 1, 1)
        self.comboBoxLed9 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed9.setObjectName("comboBoxLed9")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.comboBoxLed9.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed9, 10, 0, 1, 1)
        self.setpointEditAutomatic9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic9.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic9.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic9.setObjectName("setpointEditAutomatic9")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic9, 10, 2, 1, 1)
        self.comboBoxLed3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed3.setObjectName("comboBoxLed3")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.comboBoxLed3.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed3, 4, 0, 1, 1)
        self.setpointEditAutomatic2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic2.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic2.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic2.setObjectName("setpointEditAutomatic2")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic2, 3, 2, 1, 1)
        self.setpointEditAutomatic6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic6.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic6.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic6.setObjectName("setpointEditAutomatic6")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic6, 7, 2, 1, 1)
        self.setpointEditAutomatic1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic1.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic1.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic1.setObjectName("setpointEditAutomatic1")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic1, 2, 2, 1, 1)
        self.setpointEditAutomatic4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic4.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic4.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic4.setObjectName("setpointEditAutomatic4")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic4, 5, 2, 1, 1)
        self.setpointEditAutomatic3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic3.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic3.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic3.setObjectName("setpointEditAutomatic3")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic3, 4, 2, 1, 1)
        self.setpointEditAutomatic5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic5.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic5.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic5.setObjectName("setpointEditAutomatic5")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic5, 6, 2, 1, 1)
        self.setpointEditAutomatic8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic8.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic8.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic8.setObjectName("setpointEditAutomatic8")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic8, 9, 2, 1, 1)
        self.comboBoxLed5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed5.setObjectName("comboBoxLed5")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.comboBoxLed5.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed5, 6, 0, 1, 1)
        self.comboBoxLed2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed2.setObjectName("comboBoxLed2")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.comboBoxLed2.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed2, 3, 0, 1, 1)
        self.comboBoxLed4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed4.setObjectName("comboBoxLed4")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.comboBoxLed4.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed4, 5, 0, 1, 1)
        self.comboBoxLed0 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed0.setObjectName("comboBoxLed0")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.comboBoxLed0.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed0, 1, 0, 1, 1)
        self.spinBoxPwm6 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm6.setEnabled(True)
        self.spinBoxPwm6.setMaximum(100)
        self.spinBoxPwm6.setObjectName("spinBoxPwm6")
        self.gridLayout_2.addWidget(self.spinBoxPwm6, 7, 1, 1, 1)
        self.spinBoxPwm7 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm7.setEnabled(True)
        self.spinBoxPwm7.setMaximum(100)
        self.spinBoxPwm7.setObjectName("spinBoxPwm7")
        self.gridLayout_2.addWidget(self.spinBoxPwm7, 8, 1, 1, 1)
        self.spinBoxPwm3 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm3.setEnabled(True)
        self.spinBoxPwm3.setMaximum(100)
        self.spinBoxPwm3.setObjectName("spinBoxPwm3")
        self.gridLayout_2.addWidget(self.spinBoxPwm3, 4, 1, 1, 1)
        self.comboBoxLed1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed1.setObjectName("comboBoxLed1")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.comboBoxLed1.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed1, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 1, 1, 1)
        self.gainEditAutomatic2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic2.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic2.setSizePolicy(sizePolicy)
        self.gainEditAutomatic2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic2.setObjectName("gainEditAutomatic2")
        self.gridLayout_2.addWidget(self.gainEditAutomatic2, 3, 4, 1, 1)
        self.imagesEditAutomatic0 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic0.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic0.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic0.setObjectName("imagesEditAutomatic0")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic0, 1, 3, 1, 1)
        self.exposureEditAutomatic1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic1.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic1.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic1.setObjectName("exposureEditAutomatic1")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic1, 2, 5, 1, 1)
        self.exposureEditAutomatic0 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic0.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic0.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic0.setObjectName("exposureEditAutomatic0")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic0, 1, 5, 1, 1)
        self.gainEditAutomatic0 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic0.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic0.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic0.setSizePolicy(sizePolicy)
        self.gainEditAutomatic0.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic0.setObjectName("gainEditAutomatic0")
        self.gridLayout_2.addWidget(self.gainEditAutomatic0, 1, 4, 1, 1)
        self.gainEditAutomatic6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic6.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic6.setSizePolicy(sizePolicy)
        self.gainEditAutomatic6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic6.setObjectName("gainEditAutomatic6")
        self.gridLayout_2.addWidget(self.gainEditAutomatic6, 7, 4, 1, 1)
        self.imagesEditAutomatic8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic8.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic8.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic8.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic8.setObjectName("imagesEditAutomatic8")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic8, 9, 3, 1, 1)
        self.gainEditAutomatic7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic7.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic7.setSizePolicy(sizePolicy)
        self.gainEditAutomatic7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic7.setObjectName("gainEditAutomatic7")
        self.gridLayout_2.addWidget(self.gainEditAutomatic7, 8, 4, 1, 1)
        self.exposureEditAutomatic3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic3.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic3.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic3.setObjectName("exposureEditAutomatic3")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic3, 4, 5, 1, 1)
        self.gainEditAutomatic4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic4.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic4.setSizePolicy(sizePolicy)
        self.gainEditAutomatic4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic4.setObjectName("gainEditAutomatic4")
        self.gridLayout_2.addWidget(self.gainEditAutomatic4, 5, 4, 1, 1)
        self.imagesEditAutomatic7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic7.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic7.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic7.setObjectName("imagesEditAutomatic7")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic7, 8, 3, 1, 1)
        self.gainEditAutomatic1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic1.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic1.setSizePolicy(sizePolicy)
        self.gainEditAutomatic1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic1.setObjectName("gainEditAutomatic1")
        self.gridLayout_2.addWidget(self.gainEditAutomatic1, 2, 4, 1, 1)
        self.exposureEditAutomatic7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic7.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic7.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic7.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic7.setObjectName("exposureEditAutomatic7")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic7, 8, 5, 1, 1)
        self.imagesEditAutomatic5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic5.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic5.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic5.setObjectName("imagesEditAutomatic5")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic5, 6, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 3, 1, 1)
        self.gainEditAutomatic3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic3.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic3.setSizePolicy(sizePolicy)
        self.gainEditAutomatic3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic3.setObjectName("gainEditAutomatic3")
        self.gridLayout_2.addWidget(self.gainEditAutomatic3, 4, 4, 1, 1)
        self.gainEditAutomatic9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic9.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic9.setSizePolicy(sizePolicy)
        self.gainEditAutomatic9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic9.setObjectName("gainEditAutomatic9")
        self.gridLayout_2.addWidget(self.gainEditAutomatic9, 10, 4, 1, 1)
        self.imagesEditAutomatic2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic2.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic2.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic2.setObjectName("imagesEditAutomatic2")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic2, 3, 3, 1, 1)
        self.gainEditAutomatic5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic5.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic5.setSizePolicy(sizePolicy)
        self.gainEditAutomatic5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic5.setObjectName("gainEditAutomatic5")
        self.gridLayout_2.addWidget(self.gainEditAutomatic5, 6, 4, 1, 1)
        self.exposureEditAutomatic6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic6.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic6.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic6.setObjectName("exposureEditAutomatic6")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic6, 7, 5, 1, 1)
        self.exposureEditAutomatic5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic5.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic5.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic5.setObjectName("exposureEditAutomatic5")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic5, 6, 5, 1, 1)
        self.exposureEditAutomatic4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic4.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic4.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic4.setObjectName("exposureEditAutomatic4")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic4, 5, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 5, 1, 1)
        self.spinBoxPwm10 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBoxPwm10.setMaximum(100)
        self.spinBoxPwm10.setObjectName("spinBoxPwm10")
        self.gridLayout_2.addWidget(self.spinBoxPwm10, 11, 1, 1, 1)
        self.comboBoxLed10 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBoxLed10.setObjectName("comboBoxLed10")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.comboBoxLed10.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxLed10, 11, 0, 1, 1)
        self.setpointEditAutomatic10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.setpointEditAutomatic10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setpointEditAutomatic10.sizePolicy().hasHeightForWidth())
        self.setpointEditAutomatic10.setSizePolicy(sizePolicy)
        self.setpointEditAutomatic10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.setpointEditAutomatic10.setObjectName("setpointEditAutomatic10")
        self.gridLayout_2.addWidget(self.setpointEditAutomatic10, 11, 2, 1, 1)
        self.imagesEditAutomatic10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imagesEditAutomatic10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imagesEditAutomatic10.sizePolicy().hasHeightForWidth())
        self.imagesEditAutomatic10.setSizePolicy(sizePolicy)
        self.imagesEditAutomatic10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.imagesEditAutomatic10.setObjectName("imagesEditAutomatic10")
        self.gridLayout_2.addWidget(self.imagesEditAutomatic10, 11, 3, 1, 1)
        self.gainEditAutomatic10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gainEditAutomatic10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gainEditAutomatic10.sizePolicy().hasHeightForWidth())
        self.gainEditAutomatic10.setSizePolicy(sizePolicy)
        self.gainEditAutomatic10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gainEditAutomatic10.setObjectName("gainEditAutomatic10")
        self.gridLayout_2.addWidget(self.gainEditAutomatic10, 11, 4, 1, 1)
        self.exposureEditAutomatic10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.exposureEditAutomatic10.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exposureEditAutomatic10.sizePolicy().hasHeightForWidth())
        self.exposureEditAutomatic10.setSizePolicy(sizePolicy)
        self.exposureEditAutomatic10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.exposureEditAutomatic10.setObjectName("exposureEditAutomatic10")
        self.gridLayout_2.addWidget(self.exposureEditAutomatic10, 11, 5, 1, 1)
        self.imagePrefixEdit = QtWidgets.QLineEdit(self.automaticMode)
        self.imagePrefixEdit.setGeometry(QtCore.QRect(210, 430, 141, 25))
        self.imagePrefixEdit.setText("")
        self.imagePrefixEdit.setObjectName("imagePrefixEdit")
        self.label_23 = QtWidgets.QLabel(self.automaticMode)
        self.label_23.setGeometry(QtCore.QRect(80, 430, 121, 20))
        self.label_23.setObjectName("label_23")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.automaticMode)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(80, 460, 395, 86))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stopCamera2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopCamera2.setFont(font)
        self.stopCamera2.setObjectName("stopCamera2")
        self.gridLayout_3.addWidget(self.stopCamera2, 1, 0, 1, 1)
        self.loadAutomaticSequence = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadAutomaticSequence.setFont(font)
        self.loadAutomaticSequence.setToolTip("")
        self.loadAutomaticSequence.setToolTipDuration(-1)
        self.loadAutomaticSequence.setStatusTip("")
        self.loadAutomaticSequence.setWhatsThis("")
        self.loadAutomaticSequence.setObjectName("loadAutomaticSequence")
        self.gridLayout_3.addWidget(self.loadAutomaticSequence, 1, 2, 1, 1)
        self.automaticSavePath = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.automaticSavePath.setFont(font)
        self.automaticSavePath.setObjectName("automaticSavePath")
        self.gridLayout_3.addWidget(self.automaticSavePath, 1, 3, 1, 1)
        self.startButton3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startButton3.setFont(font)
        self.startButton3.setObjectName("startButton3")
        self.gridLayout_3.addWidget(self.startButton3, 0, 0, 1, 1)
        self.stopButton3 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopButton3.setFont(font)
        self.stopButton3.setObjectName("stopButton3")
        self.gridLayout_3.addWidget(self.stopButton3, 0, 1, 1, 1)
        self.stopAutomaticSequence = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopAutomaticSequence.setFont(font)
        self.stopAutomaticSequence.setObjectName("stopAutomaticSequence")
        self.gridLayout_3.addWidget(self.stopAutomaticSequence, 0, 3, 1, 1)
        self.startAutomaticSequence = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.startAutomaticSequence.setFont(font)
        self.startAutomaticSequence.setToolTip("")
        self.startAutomaticSequence.setToolTipDuration(-1)
        self.startAutomaticSequence.setStatusTip("")
        self.startAutomaticSequence.setWhatsThis("")
        self.startAutomaticSequence.setObjectName("startAutomaticSequence")
        self.gridLayout_3.addWidget(self.startAutomaticSequence, 0, 2, 1, 1)
        self.saveAutomaticSequence = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveAutomaticSequence.setFont(font)
        self.saveAutomaticSequence.setObjectName("saveAutomaticSequence")
        self.gridLayout_3.addWidget(self.saveAutomaticSequence, 1, 1, 1, 1)
        self.cameraTab.addTab(self.automaticMode, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cameraTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Basler camera "))
        self.groupBoxLeds.setTitle(_translate("MainWindow", "LEDs"))
        self.yellowLed.setText(_translate("MainWindow", "Yellow (595 nm)"))
        self.blueLed.setText(_translate("MainWindow", "Blue (460 nm)"))
        self.chartreuseLed.setText(_translate("MainWindow", "Chartreuse (545 nm)"))
        self.ultravioletLed.setText(_translate("MainWindow", "Ultraviolet (405 nm)"))
        self.greenLed.setText(_translate("MainWindow", "Green (515 nm)"))
        self.deepredLed.setText(_translate("MainWindow", "Deepred (640 nm)"))
        self.infraredLed.setText(_translate("MainWindow", "Infrared (725 nm)"))
        self.cyanLed.setText(_translate("MainWindow", "Cyan (495 nm)"))
        self.redLed.setText(_translate("MainWindow", "Red (625 nm)"))
        self.violetLed.setText(_translate("MainWindow", "Violet (435 nm)"))
        self.wheelLed.setText(_translate("MainWindow", "InfraredR (850 nm)"))
        self.label.setText(_translate("MainWindow", "PWM %"))
        self.ledsOffButton.setText(_translate("MainWindow", "Turn off"))
        self.groupBox.setTitle(_translate("MainWindow", "Image Format"))
        self.label_2.setText(_translate("MainWindow", "Width"))
        self.label_3.setText(_translate("MainWindow", "Height"))
        self.label_4.setText(_translate("MainWindow", "Pixel Format"))
        self.comboBoxPixelFormat.setItemText(0, _translate("MainWindow", "Mono 8"))
        self.comboBoxPixelFormat.setItemText(1, _translate("MainWindow", "Mono 12"))
        self.comboBoxPixelFormat.setItemText(2, _translate("MainWindow", "Mono 12p"))
        self.label_8.setText(_translate("MainWindow", "Output Bit"))
        self.comboBoxOutputBit.setItemText(0, _translate("MainWindow", "MSB"))
        self.comboBoxOutputBit.setItemText(1, _translate("MainWindow", "LSB"))
        self.label_9.setText(_translate("MainWindow", "Format"))
        self.comboBoxFormat.setItemText(0, _translate("MainWindow", "Png"))
        self.comboBoxFormat.setItemText(1, _translate("MainWindow", "Tiff"))
        self.comboBoxFormat.setItemText(2, _translate("MainWindow", "Raw"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Acquisition Control"))
        self.label_5.setText(_translate("MainWindow", "Exposure Auto"))
        self.comboBoxExposure.setItemText(0, _translate("MainWindow", "Cotinuous"))
        self.comboBoxExposure.setItemText(1, _translate("MainWindow", "Off"))
        self.comboBoxExposure.setItemText(2, _translate("MainWindow", "Once"))
        self.label_6.setText(_translate("MainWindow", "Exposure Time [us]"))
        self.checkBoxAFR.setText(_translate("MainWindow", "Enable Acquisition Frame Rate"))
        self.label_7.setText(_translate("MainWindow", "Acquisition Frame Rate"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Camera Information"))
        self.labelCameraInfo.setText(_translate("MainWindow", "..."))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Analog Control"))
        self.label_11.setText(_translate("MainWindow", "Gain Auto"))
        self.comboBoxGain.setItemText(0, _translate("MainWindow", "Off"))
        self.comboBoxGain.setItemText(1, _translate("MainWindow", "On"))
        self.label_12.setText(_translate("MainWindow", "Gain [dB]"))
        self.label_13.setText(_translate("MainWindow", "Gamma"))
        self.label_14.setText(_translate("MainWindow", "Digital Shift"))
        self.comboBoxDigitalShift.setItemText(0, _translate("MainWindow", "1"))
        self.comboBoxDigitalShift.setItemText(1, _translate("MainWindow", "2"))
        self.comboBoxDigitalShift.setItemText(2, _translate("MainWindow", "3"))
        self.comboBoxDigitalShift.setItemText(3, _translate("MainWindow", "4"))
        self.pushButtonSetParameters.setText(_translate("MainWindow", "Set parameters"))
        self.cameraTab.setTabText(self.cameraTab.indexOf(self.cameraParameters), _translate("MainWindow", "Camera parameters"))
        self.label_10.setText(_translate("MainWindow", "Setpoint"))
        self.label_21.setText(_translate("MainWindow", "Gain"))
        self.label_22.setText(_translate("MainWindow", "Exposure"))
        self.startButton2.setText(_translate("MainWindow", "Start video"))
        self.stopButton2.setText(_translate("MainWindow", "Stop video"))
        self.loadCalibration.setText(_translate("MainWindow", "Load"))
        self.calibrateSaveFile.setText(_translate("MainWindow", "Save file"))
        self.checkBoxcalibrate.setText(_translate("MainWindow", "Calibrate"))
        self.calibrationModeVideoState.setTitle(_translate("MainWindow", "No video feed ..."))
        self.cameraTab.setTabText(self.cameraTab.indexOf(self.calibration), _translate("MainWindow", "Calibration"))
        self.startButton.setText(_translate("MainWindow", "Start video"))
        self.stopButton.setText(_translate("MainWindow", "Stop video"))
        self.stopCamera.setText(_translate("MainWindow", "Close camera"))
        self.snapshot.setText(_translate("MainWindow", "Snapshot"))
        self.saveSnapshot.setText(_translate("MainWindow", "Save"))
        self.manualModeVideoState.setTitle(_translate("MainWindow", "No video feed ..."))
        self.cameraTab.setTabText(self.cameraTab.indexOf(self.manualMode), _translate("MainWindow", "Manual Mode"))
        self.label_17.setText(_translate("MainWindow", "Setpoint"))
        self.comboBoxLed7.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed7.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed7.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed7.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed7.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed7.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed7.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed7.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed7.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed7.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed7.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed7.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed6.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed6.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed6.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed6.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed6.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed6.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed6.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed6.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed6.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed6.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed6.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed6.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed8.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed8.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed8.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed8.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed8.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed8.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed8.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed8.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed8.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed8.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed8.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed8.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed9.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed9.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed9.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed9.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed9.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed9.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed9.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed9.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed9.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed9.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed9.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed9.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed3.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed3.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed3.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed3.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed3.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed3.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed3.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed3.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed3.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed3.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed3.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed3.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed5.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed5.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed5.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed5.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed5.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed5.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed5.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed5.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed5.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed5.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed5.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed5.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed2.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed2.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed2.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed2.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed2.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed2.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed2.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed2.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed2.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed2.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed2.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed2.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed4.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed4.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed4.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed4.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed4.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed4.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed4.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed4.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed4.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed4.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed4.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed4.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed0.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed0.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed0.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed0.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed0.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed0.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed0.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed0.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed0.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed0.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed0.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed0.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.comboBoxLed1.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed1.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed1.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed1.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed1.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed1.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed1.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed1.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed1.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed1.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed1.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed1.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.label_15.setText(_translate("MainWindow", "Led"))
        self.label_16.setText(_translate("MainWindow", "PWM"))
        self.label_18.setText(_translate("MainWindow", "Images"))
        self.label_19.setText(_translate("MainWindow", "Gain"))
        self.label_20.setText(_translate("MainWindow", "Exposure"))
        self.comboBoxLed10.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxLed10.setItemText(1, _translate("MainWindow", "Blue"))
        self.comboBoxLed10.setItemText(2, _translate("MainWindow", "Chartreuse"))
        self.comboBoxLed10.setItemText(3, _translate("MainWindow", "Cyan"))
        self.comboBoxLed10.setItemText(4, _translate("MainWindow", "Deepred"))
        self.comboBoxLed10.setItemText(5, _translate("MainWindow", "Green"))
        self.comboBoxLed10.setItemText(6, _translate("MainWindow", "Infrared"))
        self.comboBoxLed10.setItemText(7, _translate("MainWindow", "Red"))
        self.comboBoxLed10.setItemText(8, _translate("MainWindow", "Ultraviolet"))
        self.comboBoxLed10.setItemText(9, _translate("MainWindow", "Violet"))
        self.comboBoxLed10.setItemText(10, _translate("MainWindow", "Yellow"))
        self.comboBoxLed10.setItemText(11, _translate("MainWindow", "InfraredR"))
        self.label_23.setText(_translate("MainWindow", "Images file prefix:"))
        self.stopCamera2.setText(_translate("MainWindow", "Close camera"))
        self.loadAutomaticSequence.setText(_translate("MainWindow", "Load sequence"))
        self.automaticSavePath.setText(_translate("MainWindow", "Save path"))
        self.startButton3.setText(_translate("MainWindow", "Start video"))
        self.stopButton3.setText(_translate("MainWindow", "Stop video"))
        self.stopAutomaticSequence.setText(_translate("MainWindow", "Stop sequence"))
        self.startAutomaticSequence.setText(_translate("MainWindow", "Start sequence"))
        self.saveAutomaticSequence.setText(_translate("MainWindow", "Save Sequence"))
        self.cameraTab.setTabText(self.cameraTab.indexOf(self.automaticMode), _translate("MainWindow", "Automatic Mode"))


